services:
  postgres:
    image: postgres:17
    container_name: booklibrary_postgres

    environment:
      POSTGRES_DB: booklibrary
      POSTGRES_USER: booklibrary
      POSTGRES_PASSWORD: booklibrary

    ports:
      - "5433:5432"

    volumes:
      - booklibrary-postgres-data:/var/lib/postgresql/data

volumes:
  booklibrary-postgres-data: